Fix redirects to dev/null. Add tests for packages

diff --git a/assert b/assert
--- a/assert
+++ b/assert
@@ -67,6 +67,8 @@ Tests:
     --service-#NAME#-is-running
     --service-#NAME#-is-not-running
 
+    --package-#NAME#-is-installed
+
 Executing:
 $PROGNAME can be executed standalone or in a pipeline
 
@@ -122,6 +124,33 @@ run_command(){
     # Fix up the newlines
     STDOUT_REAL=`echo $STDOUT_REAL | sed ':a;N;$!ba;s/\n/ /g'`
 }
+
+os_is(){
+	if [ -f '/etc/redhat-release' ]; then 
+		echo 'redhat'
+	elif [ -f '/etc/debian_version' ]; then
+		echo 'debian'
+	else
+		echo 'unknown'
+	fi
+}
+
+pkg_is(){
+	case `os_is` in
+		redhat)
+			echo 'rpm'
+			;;
+		debian)
+			echo 'dpkg'
+			;;
+		*)
+			echo 'unkdown'
+			return 1
+			;;
+	esac
+	return 0
+}
+
 
 ##################
 # TEST FUNCTIONS #
@@ -278,7 +307,7 @@ test_file_contains(){
     if [ ! -f "$SELF_FILE" ]; then
         pfail "could not find file $SELF_FILE or it is not a regular file"
     else
-        grep -E "$CONTENT_EXPECTED" $SELF_FILE 2>&1 > /dev/null
+        grep -E "$CONTENT_EXPECTED" $SELF_FILE > /dev/null 2>&1
         if [ $? -eq 0 ]; then
             ppass "$SELF_FILE has content \"$CONTENT_EXPECTED\""
         else
@@ -291,7 +320,7 @@ test_file_contains(){
 test_process_exists(){
     local PROCESS_EXPECTED="$1"
     ptest "process $PROCESS_EXPECTED is running"
-    pgrep -x $PROCESS_EXPECTED 2>&1 > /dev/null
+    pgrep -x $PROCESS_EXPECTED > /dev/null 2>&1
     if [ $? -eq 0 ]; then
         ppass "$PROCESS_EXPECTED found"
     else
@@ -302,7 +331,7 @@ test_process_exists(){
 test_process_does_not_exist(){
     local PROCESS_EXPECTED="$1"
     ptest "process $PROCESS_EXPECTED is not running"
-    pgrep -x $PROCESS_EXPECTED 2>&1 > /dev/null
+    pgrep -x $PROCESS_EXPECTED > /dev/null 2>&1
     if [ $? -ne 0 ]; then
         ppass "$PROCESS_EXPECTED is not running"
     else
@@ -319,7 +348,7 @@ test_process_has_owner(){
         pfail "could not find the process $PROCESS_EXPECTED"
         return 1
     fi
-    pgrep -u $OWNER_EXPECTED -x $PROCESS 2>&1 > /dev/null
+    pgrep -u $OWNER_EXPECTED -x $PROCESS > /dev/null 2>&1
     if [ $? -eq 0 ]; then
         ppass "$PROCESS is owned by $OWNER_EXPECTED"
     else
@@ -348,7 +377,7 @@ test_service_is_running(){
     if [ $? -ne 0 ]; then
         pfail "could not find service $SERVICE" 
     else
-        /etc/init.d/$SERVICE status 2>&1 > /dev/null
+        /etc/init.d/$SERVICE status > /dev/null 2>&1 
         if [ $? -eq 0 ]; then
             ppass "$SERVICE is running"
         else
@@ -364,7 +393,7 @@ test_service_is_not_running(){
     if [ $? -ne 0 ]; then
         pfail "could not find service $SERVICE" 
     else
-        /etc/init.d/$SERVICE status 2>&1 > /dev/null
+        /etc/init.d/$SERVICE status > /dev/null 2>&1 
         if [ $? -eq 3 ]; then
             ppass "$SERVICE is not running"
         else
@@ -373,6 +402,34 @@ test_service_is_not_running(){
     fi
 }
 
+test_package_is_installed(){
+	local PACKAGE=$1
+	local INST=1 # assume not installed
+    ptest "package $PACKAGE is installed"
+	case `pkg_is` in
+		rpm)
+			rpm -qa | grep "$PACKAGE" > /dev/null 2>&1
+			if [ $? -eq 0 ]; then
+				INST=0
+			fi
+		;;
+		dpkg)	
+			dpkg -l "$PACKAGE" > /dev/null 2>&1
+			if [ $? -eq 0 ]; then
+				INST=0
+			fi
+		;;
+		*)
+			# Do nothing, not implemented
+		;;
+	esac
+	if [ $INST -eq 0 ]; then
+		ppass "$PACKAGE is installed"
+	else
+    	pfail "expected $PACKAGE to be installed"
+	fi 
+	
+}
 ################
 # MAIN PROGRAM #
 ################
@@ -532,7 +589,23 @@ while [ $# -gt 0 ]; do
                 ;;
             esac
         ;;
-
+	--package-*)
+            `echo $1 | grep -q "#"` || pfail "--package argument is not in the correct format"
+			# Get the package
+			SELF_PACKAGE=`echo $1 | cut -d "#" -f 2`
+			case "$1" in
+			*-is-installed)
+				shift 
+				test_package_is_installed "$SELF_PACKAGE"
+				;;
+            *)
+                echo "Unknown option $1"
+                usage
+                exit 1
+                ;;
+			esac
+			
+		;;
     --)
         shift 
         break
